using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Testing.Verifiers;

namespace ErrorProne.NET.TestHelpers
{
    public static class CodeFixTestExtensions
    {
        public static TTest WithoutGeneratedCodeVerification<TTest>(this TTest test)
            where TTest : CodeFixTest<NUnitVerifier>
        {
            test.Exclusions &= ~AnalysisExclusions.GeneratedCode;
            return test;
        }

        public static TTest WithConfigureAwaitAttributes<TTest>(this TTest test)
            where TTest : CodeFixTest<NUnitVerifier>
        {
            (string filename, string content) file = ("ConfigureAwaitAttributes.cs", @"// <auto-generated/>
[System.AttributeUsage(System.AttributeTargets.Assembly)]
internal sealed class UseConfigureAwaitFalseAttribute : System.Attribute { }

[System.AttributeUsage(System.AttributeTargets.Assembly)]
internal sealed class DoNotUseConfigureAwaitAttribute : System.Attribute { }
");

            test.TestState.Sources.Add(file);

            if (test.FixedState.Sources.Count > 0)
            {
                test.FixedState.Sources.Add(file);
            }

            if (test.BatchFixedState.Sources.Count > 0)
            {
                test.BatchFixedState.Sources.Add(file);
            }

            return test;
        }

        [System.AttributeUsage(System.AttributeTargets.Struct)]
        internal sealed class DoNotUseDefaultConstructionAttribute : System.Attribute
        {
            public DoNotUseDefaultConstructionAttribute(string? message = null) {}
        }

        [DoNotUseDefaultConstruction()]
        public struct FooBar
        {
            
        }

        [DoNotUseDefaultConstruction("Please use FooBar2.Create()")]
        public struct FooBar2
        {
            
        }
        
        public static TTest WithDoNotUseDefaultConstructionAttribute<TTest>(this TTest test)
            where TTest : CodeFixTest<NUnitVerifier>
        {
            (string filename, string content) file = ("DoNotUseDefaultConstructionAttribute.cs", @"// <auto-generated/>
[System.AttributeUsage(System.AttributeTargets.Struct)]
internal sealed class DoNotUseDefaultConstructionAttribute : System.Attribute
{
    public DoNotUseDefaultConstructionAttribute(string message = null) {}
}
");

            test.TestState.Sources.Add(file);

            if (test.FixedState.Sources.Count > 0)
            {
                test.FixedState.Sources.Add(file);
            }

            if (test.BatchFixedState.Sources.Count > 0)
            {
                test.BatchFixedState.Sources.Add(file);
            }

            return test;
        }
    }
}
